# fly.toml configuration file for 4sp_wisp
app = "4sp-wisp"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080 # This is the port your Wisp server listens on inside the container
  protocol = "tcp" # Or "udp" if your Wisp server uses UDP, but typically websockets use TCP
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[services.ports]]
    port = 80 # Expose for HTTP (redirects to HTTPS)
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443 # Expose for HTTPS (WebSockets over TLS)
    handlers = ["tls", "http"]

[services.concurrency]
  type = "connections"
  hard_limit = 25
  soft_limit = 20
# Made with ❤️ from 4SP